const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.ts']

const doc = {
  info: {
      version: "1.0.0",
      title: "Scheduling Web App",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
      {
        "name": "users",
      },
      {
        "name": "events"
      }
  ],
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/app.ts')
})

